added Book and Category tests
DmitriyK86/online-book-store pull request #11
Opened 2023-11-12 02:06 UTC by DmitriyK86

![coverage](https://github.com/DmitriyK86/online-book-store/assets/106387200/6b7a3f1f-14b0-4957-9cc8-3fcd5007d36a)

2023-11-13 13:24 UTC, okuzan requested changes

2023-11-13 13:24 UTC, okuzan commented on src/test/java/bookstore/controller/BookControllerTest.java
> +        teardown(dataSource);
teardown in after each should be enough

2023-11-13 13:24 UTC, okuzan commented on src/test/java/bookstore/controller/CategoryControllerTest.java
> +import org.testcontainers.shaded.org.apache.commons.lang3.builder.EqualsBuilder;
Using EqualsBuilder.reflectionEquals from org.testcontainers.shaded.org.apache.commons.lang3.builder is unusual. The shaded package implies it's from a JAR bundled with Testcontainers, which is not meant for direct use. You should directly depend on Apache Commons Lang for that utility.
import org.apache.commons.lang3.builder.EqualsBuilder;

2023-11-13 13:24 UTC, okuzan commented on src/test/java/bookstore/service/CategoryServiceTest.java
> +        expected.setId(categoryId);
you set it twice

2023-11-13 13:24 UTC, okuzan commented on src/test/java/bookstore/controller/CategoryControllerTest.java
> +        expected.setId(3L);
This assumes knowledge about the state of the database that might not be true

2023-11-14 11:42 UTC, kozhukhovsky approved these changes

2023-11-16 00:50 UTC, merged